In [1]:
# import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from collections import Counter
from imblearn.over_sampling import RandomOverSampler, SMOTE, BorderlineSMOTE, SVMSMOTE, ADASYN
from imblearn.under_sampling import RandomUnderSampler, NearMiss, TomekLinks
from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

# Kaggle

In [3]:
df = pd.read_csv('dataframe/UFC_Pre_kombinasi6.csv')
df.head()

,weight_class,id,B_avg_KD,B_avg_opp_KD,B_avg_SIG_STR_pct,B_avg_opp_SIG_STR_pct,B_avg_TD_pct,B_avg_opp_TD_pct,B_avg_SUB_ATT,B_avg_opp_SUB_ATT,...,R_age,gender,B_Stance_Open Stance,B_Stance_Orthodox,B_Stance_Southpaw,B_Stance_Switch,R_Stance_Open Stance,R_Stance_Orthodox,R_Stance_Southpaw,R_Stance_Switch
0,1,0,0.0,0.00,0.493750,0.448750,0.475000,0.177500,0.00000,0.125000,...,27.0,0,False,True,False,False,False,True,False,False
1,6,1,0.0,0.25,0.473125,0.371875,0.000000,0.203750,0.00000,0.500000,...,31.0,1,False,True,False,False,False,True,False,False
2,4,2,0.0,0.50,0.500000,0.480000,0.615000,0.000000,0.00000,0.000000,...,30.0,1,False,True,False,False,False,True,False,False
3,3,3,0.0,0.00,0.660000,0.690000,0.850000,0.000000,0.00000,2.000000,...,23.0,1,False,True,False,False,False,True,False,False
4,6,4,0.0,0.00,0.505312,0.439375,0.815937,0.067187,1.28125,0.640625,...,24.0,1,False,True,False,False,False,True,False,False

In [ ]:
prediction_kaggle = best_hypeparam_rfc.predict(df)
prediction_kaggle

C:\Users\fadlan\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

array(['Red', 'Blue', 'Blue', 'Red', 'Red', 'Red', 'Blue', 'Blue', 'Red',
       'Blue', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Blue', 'Red', 'Blue',
       'Blue', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Blue',
       'Red', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Blue', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Blue', 'Blue', 'Blue', 'Red', 'Red', 'Blue',
       'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red', 'Blue',
       'Blue', 'Blue', 'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Blue',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Blue',
       'Blue', 'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Blue', 'Blue', 'Blue', 'Blue', 'Blue', 'Blue',
       'Blue', 'Red', 'Blue', 'Blue', 'Blue', 'Blue', 'Blue', 'Red',
       'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Blue', 'Red', 'Blue',
       'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Blue', 'Blue', 'Blue',
       'Red', 'Red', 'Blue', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Red',
       'Blue', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Blue', 'Blue', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Blue', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Blue', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Blue', 'Blue', 'Blue',
       'Blue', 'Blue', 'Red', 'Red', 'Blue', 'Blue', 'Blue', 'Red',
       'Blue', 'Blue', 'Red', 'Red', 'Blue', 'Blue', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Blue', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Blue', 'Blue', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Blue', 'Blue', 'Blue', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Red', 'Red', 'Blue', 'Blue', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Blue', 'Red', 'Red',
       'Red', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red',
       'Blue', 'Red', 'Blue', 'Blue', 'Red', 'Blue', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red',
       'Blue', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue',
       'Red', 'Red', 'Blue', 'Blue', 'Red', 'Blue', 'Blue', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Blue', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue',
       'Red', 'Red', 'Red', 'Blue', 'Blue', 'Red', 'Blue', 'Red', 'Blue',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Blue',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Blue', 'Blue', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue',
       'Blue', 'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Blue', 'Red', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red',
       'Blue', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Red', 'Blue',
       'Blue', 'Red', 'Red', 'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red',
       'Red', 'Blue', 'Red', 'Blue', 'Red', 'Red', 'Red', 'Red', 'Red',
       'Red', 'Blue'], dtype=object)

In [ ]:
df_kaggle = pd.read_csv('dataframe/UFC_Test_Classif_X.csv')
df_kaggle.head()

,id,R_fighter,B_fighter,Referee,date,location,title_bout,weight_class,B_avg_KD,B_avg_opp_KD,...,R_win_by_Decision_Unanimous,R_win_by_KO/TKO,R_win_by_Submission,R_win_by_TKO_Doctor_Stoppage,R_Stance,R_Height_cms,R_Reach_cms,R_Weight_lbs,B_age,R_age
0,0,Tecia Torres,Juliana Lima,Chris Tognoni,2017-07-07,"Las Vegas, Nevada, USA",False,WomenStrawweight,0.0,0.00,...,4,0,0,0,Orthodox,154.94,152.40,115.0,35.0,27.0
1,1,John Howard,Lorenz Larkin,Herb Dean,2015-01-18,"Boston, Massachusetts, USA",False,Welterweight,0.0,0.25,...,1,2,0,0,Orthodox,170.18,182.88,170.0,28.0,31.0
2,2,Kyle Bochniak,Jeremy Kennedy,Todd Ronald Anderson,2017-07-22,"Uniondale, New York, USA",False,Featherweight,0.0,0.50,...,0,0,0,0,Orthodox,170.18,177.80,145.0,24.0,30.0
3,3,Yao Zhikui,Royston Wee,Steve Perceval,2014-08-23,"Macau, China",False,Bantamweight,0.0,0.00,...,0,0,0,0,Orthodox,165.10,162.56,125.0,27.0,23.0
4,4,Carlos Newton,Pat Miletich,John McCarthy,2001-05-04,"Atlantic City, New Jersey, USA",True,Welterweight,0.0,0.00,...,0,0,1,0,Orthodox,175.26,NaN,170.0,33.0,24.0

In [ ]:
df_kaggle = df_kaggle[['id']]
df_kaggle.head()

   id
0   0
1   1
2   2
3   3
4   4

In [ ]:
df_kaggle['Winner'] = pd.DataFrame({'Winner': prediction_kaggle})

In [ ]:
df_kaggle.head()

   id Winner
0   0    Red
1   1   Blue
2   2   Blue
3   3    Red
4   4    Red

In [ ]:
df_kaggle.to_csv('dataframe/Kaggle_prediction.csv', index=False)